version=0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "covid19datapuller"
s3_bucket = "sam-covid19datapuller"
s3_prefix = "covid19datapuller"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_NAMED_IAM"

